name: Build
on:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: |
          dotnet restore --locked-mode
          dotnet publish -c Release -o out --no-restore --no-restore /p:DebugType=None /p:DebugSymbols=false
        working-directory: ./AppTokenFromKms
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppTokenFromKms-${{ matrix.os }}
          path: ./AppTokenFromKms/out/
