name: Build
on:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.platform.rid }}
    strategy:
      matrix:
        platform: 
          - os: windows-2025
            rid: win-x64
            exetension: .exe
          - os: macos-14
            rid: osx-x64
            exetension: ""
          - os: ubuntu-24.04
            rid: linux-x64
            exetension: ""
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: |
          dotnet restore --locked-mode
          dotnet publish -c Release -o out --no-restore /p:DebugType=None /p:DebugSymbols=false
        working-directory: ./AppTokenFromKms
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppTokenFromKms-${{ matrix.platform.rid }}
          path: ./AppTokenFromKms/out/AppTokenFromKms${{ matrix.platform.exetension }}
